### ISSUE TITLE
Academic paper

### ISSUE THREAD

**Issue by lihua8848** [Jerry-Master/lung-tumour-study#1]
Wow, that is interesting. I am very interested in your academic papers. Could you provide me with a link to them? Thank you

**Comment by Jerry-Master** [comment]
Thanks, I have two published article unrelated to this one, you can find them here:

https://www.sciencedirect.com/science/article/abs/pii/S0957417423027987
https://www.sciencedirect.com/science/article/abs/pii/S0933365723002002

Unfortunately they are under paywall, maybe I could upload them to arxiv when i have time. The article for this repository is still under peer review. But if you want to look at the results, everything is extensively documented in here: https://github.com/Jerry-Master/BS-Thesis

**Comment by Jerry-Master** [comment]
The article of this repository has finally been published: [https://doi.org/10.1016/j.heliyon.2024.e28463](https://doi.org/10.1016/j.heliyon.2024.e28463)

**Comment by Jerry-Master** [comment]
I also updated my home page with the preprints of the other articles: [https://jerry-master.github.io/Home-Page/#articulos](https://jerry-master.github.io/Home-Page/#articulos)
